---
galaxy_info:
  author: tenhishadow
  description: User-level dotfiles linking role.
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: ArchLinux
      versions:
        - all
dependencies: []
