---
ansible:
  - changed-files:
      - any-glob-to-any-file:
          - "ansible.cfg"
          - "inventory/**/*"
          - "playbook_install.yml"
ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"
          - "renovate.json"
          - "uv.lock"
documentation:
  - changed-files:
      - any-glob-to-any-file: "README.md"
dotfiles:
  - changed-files:
      - any-glob-to-any-file:
          - "dotfiles/**/*"
nvim:
  - changed-files:
      - any-glob-to-any-file:
          - "dotfiles/.config/nvim/**/*"
bashrc:
  - changed-files:
      - any-glob-to-any-file:
          - "dotfiles/.bashrc"
