---

- hosts: this_host
  become: false
  connection: local
  gather_facts: true
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - dotfiles_mapping is defined
      tags:
        - configs

    - name: manage dirs for dotfiles
      file:
        path: "{{ item.value.dir_path }}"
        state: directory
        mode: "{{ item.value.dir_mode }}"
        owner: "{{ item.value.dir_owner }}"
        group: "{{ item.value.dir_group }}"
      loop: "{{ dotfiles_mapping | dict2items }}"
      loop_control:
        label: "{{ item | json_query('value.dir_path') }}"
      when:
        - item.value.dir_path is defined
        - item.value.dir_mode is defined
        - item.value.dir_owner is defined
        - item.value.dir_group is defined
      tags:
        - configs

    - name: create symlinks for dotfiles
      file:
        src: "{{ item.value.src }}"
        dest: "{{ item.value.dest }}"
        force: true
        state: link
      loop: "{{ dotfiles_mapping | dict2items }}"
      loop_control:
        label: "{{ item | json_query('value.dest') }}"
      tags:
        - configs

    - name: dotfiles | cronjob for vim-plug update
      cron:
        name: vim-plug update/upgrade
        job: 'vim +PlugUpgrade +PlugUpdate +qa! >/dev/null'
        special_time: weekly
      ignore_errors: true  # if cron not presented
      no_log: true         # it doesnt matter

    - name: dotfiles | cronjob for update
      cron:
        name: dotfiles updates
        job: "cd {{ ansible_user_dir }}/.dotfiles && git pull"
        special_time: hourly
      ignore_errors: true # if cron not presented

...
