---

- hosts: this_host
  become: false
  connection: local
  gather_facts: true
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - dotfiles_mapping is defined

    - name: manage dirs for dotfiles
      file:
        path: "{{ item.value.dir_path }}"
        state: directory
        mode: "{{ item.value.dir_mode }}"
        owner: "{{ item.value.dir_owner }}"
        group: "{{ item.value.dir_group }}"
      with_dict: "{{ dotfiles_mapping }}"
      when:
        - item.value.dir_path is defined
        - item.value.dir_mode is defined
        - item.value.dir_owner is defined
        - item.value.dir_group is defined

    - name: create symlinks for dotfiles
      file:
        src: "{{ item.value.src }}"
        dest: "{{ item.value.dest }}"
        force: true
        state: link
      with_dict: "{{ dotfiles_mapping }}"

    - name: manage vim-plug update
      cron:
        name: vim-plug update/upgrade
        job: 'vim +PlugUpgrade +PlugUpdate +qa! >/dev/null'
        special_time: weekly
      ignore_errors: true  # if cron not presented
      no_log: true         # it doesnt matter

...
