---
- name: Apply user dotfiles
  hosts: this_host
  become: false
  connection: local
  gather_facts: true
  tasks:
    - name: Dotfiles | Validate mapping
      ansible.builtin.assert:
        that:
          - dotfiles_mapping is defined
      tags:
        - configs

    - name: Dotfiles | Ensure parent directories
      ansible.builtin.file:
        path: "{{ item.value.dir_path }}"
        state: directory
        mode: "{{ item.value.dir_mode }}"
        owner: "{{ item.value.dir_owner }}"
        group: "{{ item.value.dir_group }}"
      loop: "{{ dotfiles_mapping | dict2items }}"
      loop_control:
        label: "{{ item | json_query('value.dir_path') }}"
      when:
        - item.value.dir_path is defined
        - item.value.dir_mode is defined
        - item.value.dir_owner is defined
        - item.value.dir_group is defined
      tags:
        - configs

    - name: Dotfiles | Link payload
      ansible.builtin.file:
        src: "{{ item.value.src }}"
        dest: "{{ item.value.dest }}"
        force: true
        state: link
      loop: "{{ dotfiles_mapping | dict2items }}"
      loop_control:
        label: "{{ item | json_query('value.dest') }}"
      tags:
        - configs

    - name: Dotfiles | Remove legacy paths
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ dotfiles_cleanup }}"
      tags:
        - configs

    - name: Dotfiles | Check crontab
      ansible.builtin.stat:
        path: /usr/bin/crontab
      register: dotfiles_crontab_bin
      changed_when: false

    - name: Dotfiles | Schedule Neovim restore
      ansible.builtin.cron:
        state: present
        name: vim-plug update/upgrade
        job: 'nvim --headless "+Lazy! restore" +qa > ~/.nvim.log 2>&1'
        special_time: daily
      when:
        - dotfiles_crontab_bin.stat.exists | default(false)

    - name: Dotfiles | Remove legacy update cron
      ansible.builtin.cron:
        state: absent
        name: dotfiles updates
      when:
        - dotfiles_crontab_bin.stat.exists | default(false)

    - name: Dotfiles | Remove .pam_environment
      ansible.builtin.file:
        path: "{{ ansible_facts.user_dir }}/.pam_environment"
        state: absent
