[project]
requires-python = ">=3.13"
name = "dotfiles"
version = "2.5.0"
dependencies = [
    "ansible",
]

[dependency-groups]
dev = [
    "ansible-lint",
    "pre-commit",
    "pylint",
    "pytest",
    "pyyaml",
    "ruff",
    "yamllint",
    "vim-vint",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
testpaths = [".test"]
pythonpath = [".test", ".github/scripts"]
addopts = "-ra --strict-config --strict-markers --import-mode=importlib"
norecursedirs = ["nvim", "system"]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
