[project]
requires-python = ">=3.14"
name = "dotfiles"
version = "2.4.1"
dependencies = [
    "ansible",
    "ansible-lint",
    "pre-commit",
    "pylint",
    "pyyaml",
    "ruff",
    "yamllint",
    "vim-vint",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
