collections:
  - name: ansible.posix
    version: "2.2.0"
    source: https://galaxy.ansible.com
  - name: community.general
    version: "13.0.0"
    source: https://galaxy.ansible.com
  - name: serverscom.mitogen
    version: "1.4.1"
    source: https://galaxy.ansible.com
