# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  RUN_PLAYBOOK: "uv run ansible-playbook playbook_install.yml {{.CLI_ARGS}}"
  DEPS_OS_ARCHLINUX: "uv git"
  MITOGEN_VARS: "ANSIBLE_STRATEGY=serverscom.mitogen.mitogen_linear"

tasks:
  deps-os:
    status:
      - sh -c 'type -P uv'
    cmds:
      - which uv
  #     - task: deps-os:arch
  #     - task: deps-os:unsupported
  # deps-os:arch:
  #   internal: true
  #   status:
  #     - ! grep -q Arch /etc/*release*
  #   cmd: >-
  #     sudo pacman -Sy --noconfirm {{.DEPS_OS_ARCHLINUX}}
  #     || pacman -Sy --noconfirm {{.DEPS_OS_ARCHLINUX}}
  # deps-os:unsupported:
  #   internal: true
  #   status:
  #     - grep -q Arch /etc/*release*
  #   cmds:
  #     - echo OS is not supported

  deps-python:
    silent: true
    deps: [deps-os]
    cmds:
      - uv sync --locked
  deps-galaxy:
    silent: true
    deps: [deps-python]
    cmds:
      - "uv run ansible-galaxy install -r requirements.yml"
  deps-upgrade:
    cmds:
      - uv sync --upgrade
  lint:
    deps: [deps-python]
    cmds:
      - "uv run ansible-lint"
  clear:
    cmd: >-
      rm -rf
      .ansible
      .collections
      .task
      .venv
  default:
    deps: [deps-galaxy]
    cmd: "{{.MITOGEN_VARS}} {{.RUN_PLAYBOOK}}"
  nvim:
    deps: [default]
    cmds:
      - nvim --headless "+Lazy! restore" +qa
      - nvim --headless "+checkhealth" +qa
      - nvim --headless "+checkhealth vim.lsp" +qa
      - nvim
