# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  playbook: playbook_install.yml

tasks:
  deps:
    sources:
      - pyproject.toml
      - uv.lock
    generates:
      - .venv/pyvenv.cfg
    cmds:
      - uv sync --all-extras --dev
    silent: true
  pre-deps:
    cmd: >-
      false
      ||
      echo 123 && echo 333
    #   sudo pacman -Sy --noconfirm python-pipenv python-setuptools
    #   ||
    #   sudo apt install git pipenv -y
    # && apt-get update \
    # && apt-get install -y --no-install-recommends \
  default:
    deps: [deps]
    cmds:
      - uv run ansible-playbook {{.playbook}}
  lint:
    deps: [deps]
    cmds:
      - uv run ansible-lint {{.playbook}}
  configs:
    deps: [deps]
    cmds:
      - uv run ansible-playbook {{.playbook}} --tags configs
  upgrade:
    cmds:
      - uv sync --upgrade
  nvim:
    cmds:
      - nvim --headless "+Lazy! sync" +qa
