# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  RUN_PLAYBOOK: "uv run ansible-playbook playbook_install.yml {{.CLI_ARGS}}"
  DEPS_OS_ARCHLINUX: "pacman -Sy --noconfirm --needed --noprogressbar uv git"
  MITOGEN_VARS: "ANSIBLE_STRATEGY=serverscom.mitogen.mitogen_linear"

tasks:
  deps-os:
    status:
      - $SHELL -c 'type -P uv'
    cmd: >-
      {{.DEPS_OS_ARCHLINUX}}
      || sudo {{.DEPS_OS_ARCHLINUX}}
  deps-python:
    silent: true
    deps: [deps-os]
    cmd: >-
      uv sync
      --locked
      --no-build
      --no-install-project
      --no-dev
      --managed-python
      --quiet
  deps-galaxy:
    silent: true
    deps: [deps-python]
    cmds:
      - "uv run ansible-galaxy install -r requirements.yml"
  deps-upgrade:
    cmds:
      - uv sync --upgrade

  lint:
    deps: [deps-python]
    cmds:
      - "uv run ansible-lint"
  clear:
    cmd: >-
      rm -rf
      .ansible
      .collections
      .task
      .venv
  default:
    deps: [deps-galaxy]
    cmd: "{{.MITOGEN_VARS}} {{.RUN_PLAYBOOK}}"
  nvim:
    deps: [default]
    cmds:
      - nvim --headless "+Lazy! restore" +qa
      - nvim --headless "+checkhealth" +qa
      - nvim --headless "+checkhealth vim.lsp" +qa
      - nvim
