local repo_root = vim.fn.getcwd()
local nvim_lua = repo_root .. "/dotfiles/.config/nvim/lua"

package.path = table.concat({
  nvim_lua .. "/?.lua",
  nvim_lua .. "/?/init.lua",
  package.path,
}, ";")

local keymaps = require("config.keymaps_spec")

local mode_labels = {
  c = "Command",
  i = "Insert",
  n = "Normal",
  o = "Operator",
  s = "Select",
  t = "Terminal",
  v = "Visual",
  x = "Visual",
}

local function as_list(value)
  if type(value) == "table" then
    return value
  end
  return { value }
end

local function mode_label(mode)
  return mode_labels[mode] or mode
end

local function mode_text(modes)
  local labels = {}
  for _, mode in ipairs(as_list(modes)) do
    table.insert(labels, mode_label(mode))
  end
  return table.concat(labels, ", ")
end

local function key_text(lhs)
  local tokens = {}
  local index = 1

  while index <= #lhs do
    local rest = lhs:sub(index)

    if rest:sub(1, #"<leader>") == "<leader>" then
      table.insert(tokens, keymaps.leader.label)
      index = index + #"<leader>"
    elseif rest:sub(1, #"<localleader>") == "<localleader>" then
      table.insert(tokens, keymaps.localleader.label)
      index = index + #"<localleader>"
    elseif lhs:sub(index, index) == "<" then
      local close = lhs:find(">", index, true)
      if close then
        local token = lhs:sub(index, close)
        token = token:gsub("^<F(%d+)>$", "F%1")
        token = token:gsub("^<CR>$", "Enter")
        table.insert(tokens, token)
        index = close + 1
      else
        table.insert(tokens, lhs:sub(index, index))
        index = index + 1
      end
    else
      table.insert(tokens, lhs:sub(index, index))
      index = index + 1
    end
  end

  return table.concat(tokens, " ")
end

local function markdown_escape(value)
  return tostring(value):gsub("|", "\\|")
end

local function validate()
  local seen = {}

  for _, section in ipairs(keymaps.sections) do
    for _, keymap in ipairs(section.maps) do
      for _, mode in ipairs(as_list(keymap.mode)) do
        local key = mode .. "\t" .. keymap.lhs
        local existing = seen[key]
        if existing then
          error(
            ("duplicate keymap %s %s in %s and %s"):format(
              mode,
              keymap.lhs,
              existing,
              section.name
            )
          )
        end
        seen[key] = section.name
      end
    end
  end
end

local function emit(lines, value)
  table.insert(lines, value)
end

validate()

local lines = {}

emit(lines, "# Neovim Keymaps")
emit(lines, "")
emit(lines, "Generated from `dotfiles/.config/nvim/lua/config/keymaps_spec.lua`.")
emit(lines, "Do not edit this file by hand. Run `go-task docs:nvim-keymaps`.")
emit(lines, "")
emit(lines, ("Leader key: `%s` (`%s`)."):format(keymaps.leader.label, keymaps.leader.notation))
emit(
  lines,
  ("Local leader key: `%s` (`%s`)."):format(keymaps.localleader.label, keymaps.localleader.notation)
)
emit(lines, "")
emit(lines, "Read key combinations from left to right. For example, `Space h s` means press Space, then h, then s.")

for _, section in ipairs(keymaps.sections) do
  emit(lines, "")
  emit(lines, "## " .. section.name)
  emit(lines, "")
  emit(lines, "| Keys | Mode | Action |")
  emit(lines, "| ---- | ---- | ------ |")

  for _, keymap in ipairs(section.maps) do
    emit(
      lines,
      ("| `%s` | %s | %s |"):format(
        markdown_escape(key_text(keymap.lhs)),
        markdown_escape(mode_text(keymap.mode)),
        markdown_escape(keymap.desc)
      )
    )
  end
end

io.write(table.concat(lines, "\n"))
io.write("\n")
