-- Curated package snapshot from mason-org/mason-registry at the pinned commit.

return {
  registry_commit = "c3d46b83801c551dc1a46d31b46272e3b514236b",
  packages = {
    "actionlint",
    "ansible-language-server",
    "ansible-lint",
    "awk-language-server",
    "azure-pipelines-language-server",
    "bash-language-server",
    "basics-language-server",
    "black",
    "circleci-yaml-language-server",
    "commitlint",
    "copilot-language-server",
    "cue",
    "docker-compose-language-service",
    "dockerfile-language-server",
    "dotenv-linter",
    "eslint-lsp",
    "gh-actions-language-server",
    "gitlab-ci-ls",
    "gitleaks",
    "google-java-format",
    "gopls",
    "gradle-language-server",
    "graphql-language-service-cli",
    "hadolint",
    "hclfmt",
    "helm-ls",
    "isort",
    "jq-lsp",
    "json-lsp",
    "jsonlint",
    "jsonnet-language-server",
    "jsonnetfmt",
    "kube-linter",
    "lua-language-server",
    "markdownlint-cli2",
    "opa",
    "postgres-language-server",
    "prometheus-pint",
    "pyright",
    "regal",
    "regols",
    "ruby-lsp",
    "ruff",
    "semgrep",
    "shellcheck",
    "sqlfluff",
    "systemd-lsp",
    "systemdlint",
    "terraform-ls",
    "tflint",
    "tofu-ls",
    "trivy",
    "typescript-language-server",
    "yaml-language-server",
    "yamllint",
  },
  lspconfig_to_package = {
    ansiblels = "ansible-language-server",
    bashls = "bash-language-server",
    cue = "cue",
    docker_compose_language_service = "docker-compose-language-service",
    dockerls = "dockerfile-language-server",
    eslint = "eslint-lsp",
    gh_actions_ls = "gh-actions-language-server",
    gitlab_ci_ls = "gitlab-ci-ls",
    gopls = "gopls",
    helm_ls = "helm-ls",
    jsonls = "json-lsp",
    jsonnet_ls = "jsonnet-language-server",
    lua_ls = "lua-language-server",
    pyright = "pyright",
    regols = "regols",
    ruby_lsp = "ruby-lsp",
    terraformls = "terraform-ls",
    tofu_ls = "tofu-ls",
    ts_ls = "typescript-language-server",
    yamlls = "yaml-language-server",
  },
}
