---
- name: Sysctl | Write kernel parameter drop-in
  become: true
  ansible.builtin.template:
    src: sysctl-dropin.conf.j2
    dest: "{{ system_sysctl_file_path }}"
    owner: "{{ system_config_owner }}"
    group: "{{ system_config_group }}"
    mode: "{{ system_config_file_mode }}"
    backup: true
  vars:
    system_sysctl_combined_settings: >-
      {{ system_sysctl_default_settings | combine(system_sysctl_settings) }}
  when:
    - not (system_is_container | bool)
    - not (system_in_ci | bool)
  notify: Sysctl | Reload settings
