---
- name: Sysctl | Apply kernel parameters
  become: true
  ansible.posix.sysctl:
    name: "{{ system_sysctl_setting.key }}"
    value: "{{ system_sysctl_setting.value }}"
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: "{{ system_sysctl_file_path }}"
  loop: >-
    {{
      system_sysctl_default_settings
      | combine(system_sysctl_settings)
      | dict2items
    }}
  loop_control:
    loop_var: system_sysctl_setting
    label: "{{ system_sysctl_setting.key }}"
  when:
    - system_sysctl_enabled | bool
    - not (system_is_container | bool)
    - not (system_in_ci | bool)
