---
- name: Locale | Check locale definitions
  ansible.builtin.stat:
    path: "{{ system_locale_definition.1 }}/{{ system_locale_definition.0 }}"
  loop: "{{ system_locales | product(system_locale_definition_dirs) | list }}"
  loop_control:
    loop_var: system_locale_definition
    label: "{{ system_locale_definition.1 }}/{{ system_locale_definition.0 }}"
  register: system_locale_definition_stats
  changed_when: false

- name: Locale | Build available locale list
  ansible.builtin.set_fact:
    system_locale_available_names: "{{ system_locale_available_names_tmp }}"
    system_locale_missing_definitions: "{{ system_locales | difference(system_locale_available_names_tmp) }}"
  vars:
    system_locale_available_names_tmp: >-
      {{ system_locale_definition_stats.results
         | selectattr('stat.exists')
         | map(attribute='system_locale_definition.0')
         | unique
         | list }}

- name: Locale | Write locale.gen
  become: true
  ansible.builtin.template:
    backup: true
    src: templates/locale.gen.j2
    dest: "{{ system_locale_gen_path }}"
    owner: "{{ system_config_owner }}"
    group: "{{ system_config_group }}"
    mode: "{{ system_config_file_mode }}"
  notify:
    - Console | Restart vconsole setup

- name: Locale | Write locale.conf
  become: true
  ansible.builtin.template:
    backup: true
    src: templates/locale.conf.j2
    dest: "{{ system_locale_conf_path }}"
    owner: "{{ system_config_owner }}"
    group: "{{ system_config_group }}"
    mode: "{{ system_config_file_mode }}"
  notify:
    - Console | Restart vconsole setup

- name: Locale | Read generated locale list
  become: true
  ansible.builtin.command: locale -a
  register: system_locale_list
  changed_when: false

- name: Locale | Generate missing locales
  become: true
  ansible.builtin.command: locale-gen
  changed_when: true
  vars:
    system_locale_desired_names: >-
      {{ system_locale_available_names
         | map('regex_replace', '$', '.utf8')
         | map('lower')
         | list }}
    system_locale_current_names: "{{ system_locale_list.stdout_lines | map('lower') | list }}"
    system_locale_missing_names: >-
      {{ system_locale_desired_names | difference(system_locale_current_names) }}
  when:
    - not (system_in_ci | bool)
    - system_locale_missing_names | length > 0
