---
- name: Locale | Check locale definitions
  ansible.builtin.stat:
    path: "{{ system_locale_definition_dir }}/{{ system_locale_name }}"
  loop: "{{ system_locales }}"
  loop_control:
    loop_var: system_locale_name
    label: "{{ system_locale_name }}"
  register: system_locale_definition_stats
  changed_when: false
  when:
    - not (system_is_container | bool)

- name: Locale | Validate locale definitions
  ansible.builtin.assert:
    that:
      - system_locale_definition_stat.stat.exists
      - system_locale_definition_stat.stat.isreg
    fail_msg: "Missing locale definition: {{ system_locale_definition_stat.system_locale_name }}"
    quiet: true
  loop: "{{ system_locale_definition_stats.results }}"
  loop_control:
    loop_var: system_locale_definition_stat
    label: "{{ system_locale_definition_stat.system_locale_name }}"
  when:
    - not (system_is_container | bool)

- name: Locale | Write locale.gen
  become: true
  ansible.builtin.template:
    backup: true
    src: templates/locale.gen.j2
    dest: "{{ system_locale_gen_path }}"
    owner: "{{ system_config_owner }}"
    group: "{{ system_config_group }}"
    mode: "{{ system_config_file_mode }}"
  register: system_locale_gen_result
  notify:
    - Console | Restart vconsole setup

- name: Locale | Write locale.conf
  become: true
  ansible.builtin.template:
    backup: true
    src: templates/locale.conf.j2
    dest: "{{ system_locale_conf_path }}"
    owner: "{{ system_config_owner }}"
    group: "{{ system_config_group }}"
    mode: "{{ system_config_file_mode }}"
  notify:
    - Console | Restart vconsole setup

- name: Locale | Generate configured locales
  become: true
  ansible.builtin.command: locale-gen
  changed_when: true
  when:
    - not (system_in_ci | bool)
    - system_locale_gen_result is changed
