---
- name: Chromium Policies | Build managed targets
  ansible.builtin.set_fact:
    browser_policies_policy_files: "{{ browser_policies_chromium_policy_files }}"
  vars:
    browser_policies_chromium_extension_settings_merged: >-
      {{
        browser_policies_extension_block
        | combine(
            browser_policies_chromium_extension_settings,
            recursive=True
          )
      }}
    browser_policies_chromium_policy_files: >-
      {%- set browser_policies_chromium_files = [] -%}
      {%- for browser_policies_chromium_target in browser_policies_chromium_targets -%}
      {%-   if browser_policies_chromium_target.enabled | default(true) | bool -%}
      {%-     set browser_policies_chromium_filename = browser_policies_chromium_target.policy_filename | default(browser_policies_chromium_policy_filename) -%}
      {%-     set browser_policies_chromium_content =
                browser_policies_chromium_base_policies
                | combine(browser_policies_chromium_target.policies | default({}), recursive=True)
                | combine(
                    (
                      browser_policies_chromium_extension_settings_merged
                      | length > 0
                    )
                    | ternary(
                        {
                          'ExtensionSettings':
                            browser_policies_chromium_extension_settings_merged,
                        },
                        {}
                      ),
                    recursive=True
                  )
      -%}
      {%-     set browser_policies_chromium_file_added = browser_policies_chromium_files.append(
                {
                  'name': browser_policies_chromium_target.name,
                  'family': 'Chromium',
                  'directory': browser_policies_chromium_target.policy_dir,
                  'path': browser_policies_chromium_target.policy_dir ~ '/' ~ browser_policies_chromium_filename,
                  'content': browser_policies_chromium_content,
                }
              )
      -%}
      {%-   endif -%}
      {%- endfor -%}
      {{ browser_policies_chromium_files }}

- name: Chromium Policies | Run policy file tasks
  ansible.builtin.include_tasks:
    file: policy-files.yml
  when:
    - browser_policies_policy_files | length > 0
