---
- name: Firefox Policies | Build managed targets
  ansible.builtin.set_fact:
    browser_policies_policy_files: "{{ browser_policies_firefox_policy_files }}"
  vars:
    browser_policies_firefox_extension_settings_merged: >-
      {{
        browser_policies_extension_block
        | combine(
            browser_policies_firefox_extension_settings,
            recursive=True
          )
      }}
    browser_policies_firefox_policy_files: >-
      {%- set browser_policies_firefox_files = [] -%}
      {%- for browser_policies_firefox_target in browser_policies_firefox_targets -%}
      {%-   if browser_policies_firefox_target.enabled | default(true) | bool -%}
      {%-     set browser_policies_firefox_policy =
                browser_policies_firefox_base_policies
                | combine(browser_policies_firefox_target.policies | default({}), recursive=True)
                | combine(
                    (
                      browser_policies_firefox_extension_settings_merged
                      | length > 0
                    )
                    | ternary(
                        {
                          'ExtensionSettings':
                            browser_policies_firefox_extension_settings_merged,
                        },
                        {}
                      ),
                    recursive=True
                  )
      -%}
      {%-     set browser_policies_firefox_file_added = browser_policies_firefox_files.append(
                {
                  'name': browser_policies_firefox_target.name,
                  'family': 'Firefox',
                  'directory': browser_policies_firefox_target.policy_path | dirname,
                  'path': browser_policies_firefox_target.policy_path,
                  'content': {'policies': browser_policies_firefox_policy},
                }
              )
      -%}
      {%-   endif -%}
      {%- endfor -%}
      {{ browser_policies_firefox_files }}

- name: Firefox Policies | Run policy file tasks
  ansible.builtin.include_tasks:
    file: policy-files.yml
  when:
    - browser_policies_policy_files | length > 0
