---
- name: Browser Policies | Validate inputs
  ansible.builtin.include_tasks: validate.yml
  when:
    - browser_policies_enabled | bool
  tags:
    - browser_policies
    - browser_policies_validate

- name: Browser Policies | Run Chromium tasks
  ansible.builtin.include_tasks: chromium.yml
  when:
    - browser_policies_enabled | bool
    - browser_policies_chromium_enabled | bool
  tags:
    - browser_policies
    - browser_policies_chromium

- name: Browser Policies | Run Firefox tasks
  ansible.builtin.include_tasks: firefox.yml
  when:
    - browser_policies_enabled | bool
    - browser_policies_firefox_enabled | bool
  tags:
    - browser_policies
    - browser_policies_firefox

- name: Browser Policies | Run VS Code tasks
  ansible.builtin.include_tasks: vscode.yml
  when:
    - browser_policies_enabled | bool
    - browser_policies_vscode_enabled | bool
  tags:
    - browser_policies
    - browser_policies_vscode
