---
- name: Browser Policies | Validate inputs
  ansible.builtin.include_tasks: validate.yml
  when:
    - browser_policies_enabled | bool
  tags:
    - browser_policies
    - browser_policies_validate

- name: Browser Policies | Run Chromium tasks
  ansible.builtin.include_tasks: build-policy-files.yml
  vars:
    browser_policies_family: "{{ browser_policies_families | selectattr('key', 'equalto', 'chromium') | first }}"
  when:
    - browser_policies_enabled | bool
    - browser_policies_chromium_enabled | bool
  tags:
    - browser_policies
    - browser_policies_chromium

- name: Browser Policies | Run Firefox tasks
  ansible.builtin.include_tasks: build-policy-files.yml
  vars:
    browser_policies_family: "{{ browser_policies_families | selectattr('key', 'equalto', 'firefox') | first }}"
  when:
    - browser_policies_enabled | bool
    - browser_policies_firefox_enabled | bool
  tags:
    - browser_policies
    - browser_policies_firefox

- name: Browser Policies | Run Thunderbird tasks
  ansible.builtin.include_tasks: build-policy-files.yml
  vars:
    browser_policies_family: "{{ browser_policies_families | selectattr('key', 'equalto', 'thunderbird') | first }}"
  when:
    - browser_policies_enabled | bool
    - browser_policies_thunderbird_enabled | bool
  tags:
    - browser_policies
    - browser_policies_thunderbird

- name: Browser Policies | Run VS Code tasks
  ansible.builtin.include_tasks: build-policy-files.yml
  vars:
    browser_policies_family: "{{ browser_policies_families | selectattr('key', 'equalto', 'vscode') | first }}"
  when:
    - browser_policies_enabled | bool
    - browser_policies_vscode_enabled | bool
  tags:
    - browser_policies
    - browser_policies_vscode
