---
- name: VS Code Policies | Build managed targets
  ansible.builtin.set_fact:
    browser_policies_policy_files: "{{ browser_policies_vscode_policy_files }}"
  vars:
    browser_policies_vscode_policy_files: >-
      {%- set browser_policies_vscode_files = [] -%}
      {%- for browser_policies_vscode_target in browser_policies_vscode_targets -%}
      {%-   if browser_policies_vscode_target.enabled | default(true) | bool -%}
      {%-     set browser_policies_vscode_content =
                browser_policies_vscode_base_policies
                | combine(browser_policies_vscode_target.policies | default({}), recursive=True)
                | combine(
                    (
                      browser_policies_vscode_allowed_extensions | length > 0
                    )
                    | ternary(
                        {
                          'AllowedExtensions':
                            browser_policies_vscode_allowed_extensions | to_json,
                        },
                        {}
                      ),
                    recursive=True
                  )
      -%}
      {%-     set browser_policies_vscode_file_added = browser_policies_vscode_files.append(
                {
                  'name': browser_policies_vscode_target.name,
                  'family': 'VS Code',
                  'directory': browser_policies_vscode_target.policy_path | dirname,
                  'path': browser_policies_vscode_target.policy_path,
                  'content': browser_policies_vscode_content,
                }
              )
      -%}
      {%-   endif -%}
      {%- endfor -%}
      {{ browser_policies_vscode_files }}

- name: VS Code Policies | Run policy file tasks
  ansible.builtin.include_tasks:
    file: policy-files.yml
  when:
    - browser_policies_policy_files | length > 0
