---
- name: Journald | Restart service
  become: true
  ansible.builtin.service:
    name: "{{ system_journald_service_name }}"
    state: restarted

- name: SSHD | Restart service
  become: true
  ansible.builtin.service:
    name: "{{ system_sshd_service_name }}"
    state: restarted
    enabled: true

- name: Docker | Restart service
  become: true
  ansible.builtin.service:
    name: "{{ system_docker_service_name }}"
    state: restarted

- name: NTP | Restart service
  become: true
  ansible.builtin.service:
    name: "{{ system_ntp_service }}"
    state: restarted
    enabled: true
  when:
    - system_can_manage_systemd | default(false) | bool

- name: Console | Restart vconsole setup
  become: true
  ansible.builtin.service:
    name: "{{ system_vconsole_service_name }}"
    state: restarted
  when:
    - system_can_manage_systemd | default(false) | bool

- name: User systemd | Restart ssh-agent
  ansible.builtin.systemd_service:
    scope: user
    name: "{{ system_ssh_agent_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
