SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"
GEMINI_TELEMETRY_ENABLED=false
GEMINI_TELEMETRY_TRACES_ENABLED=false
GEMINI_TELEMETRY_LOG_PROMPTS=false
GEMINI_TELEMETRY_USE_COLLECTOR=false
NO_UPDATE_NOTIFIER=1
YARN_ENABLE_TELEMETRY=false
