---
galaxy_info:
  author: tenhishadow
  description: Manage system-wide browser and VS Code enterprise policies on Linux.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: ArchLinux
      versions:
        - all
dependencies: []
