---
system_sshd_settings:
  Port: "22"
  AddressFamily: "any"
  UseDNS: "no"
  SyslogFacility: "AUTHPRIV"
  LoginGraceTime: "1m"
  StrictModes: "yes"
  MaxAuthTries: "20"
  MaxSessions: "100"
  PermitRootLogin: "prohibit-password"
  PubkeyAuthentication: "yes"
  IgnoreRhosts: "yes"
  PasswordAuthentication: "yes" # pragma: allowlist secret
  PermitEmptyPasswords: "no"
  ClientAliveInterval: "300"
  AllowAgentForwarding: "yes"
  AllowTcpForwarding: "yes"
  ClientAliveCountMax: "2"
  UnusedConnectionTimeout: "300"
  RequiredRSASize: "2048"
  KerberosAuthentication: "no"
  Ciphers: "aes256-gcm@openssh.com,aes256-ctr"
  MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com"
  KexAlgorithms: "sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512"
  HostKeyAlgorithms: "ssh-ed25519,rsa-sha2-512,rsa-sha2-256"

system_sysctl_enabled: true
system_sysctl_settings:
  fs.file-max: "2097152"
  fs.inotify.max_queued_events: "32768"
  fs.inotify.max_user_instances: "8192"
  fs.inotify.max_user_watches: "524288"
  net.ipv4.tcp_rfc1337: "1"
  net.ipv4.tcp_syncookies: "1"
  vm.swappiness: "10"
  vm.dirty_background_ratio: "5"
  vm.dirty_expire_centisecs: "3000"
  vm.dirty_ratio: "10"
  vm.dirty_writeback_centisecs: "500"
  vm.mmap_min_addr: "65536"
  vm.overcommit_memory: "0"
  vm.vfs_cache_pressure: "100"
  vm.zone_reclaim_mode: "0"
  net.ipv6.conf.default.disable_ipv6: "1"
  net.ipv6.conf.lo.disable_ipv6: "1"
  net.ipv6.conf.all.disable_ipv6: "1"
