---

name: ansible_exec

on: [push, pull_request]

jobs:
  ansible_exec:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:

      - name: do checkout
        uses: actions/checkout@master

      - name: deps | python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: deps | virtualenv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      - name: just do it!
        run: bash exec.sh
        env:
          ANSIBLE_FORCE_COLOR: true

...
