---

name: ansible_lint

permissions:
  contents: read

on:
  pull_request:

jobs:
  ansible_lint:
    runs-on: ubuntu-latest

    steps:

      - name: do checkout
        uses: actions/checkout@master

      - name: deps | python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: cache | pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: lint-pip
          restore-keys: |
            lint-pip-

      - name: deps | install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: deps | pipenv install
        run: pipenv install --dev

      - name: lint
        run: pipenv run lint
        env:
          ANSIBLE_FORCE_COLOR: true

...
