---

name: ansible_exec

on:
  push:
  pull_request:
  schedule:
    - cron: '5 13 * * *'


jobs:
  ansible_exec:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: do checkout
        uses: actions/checkout@master

      - name: deps | python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: deps | pipenv
        uses: dschep/install-pipenv-action@v1

      - name: just do it!
        run: pipenv run install
        env:
          ANSIBLE_FORCE_COLOR: true

...
