---
name: "github-super-linter"

permissions:
  contents: read

on:
  pull_request:

jobs:
  github-super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Scan Code Base
        uses: super-linter/super-linter@v8.5.0
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_LUA: false
          VALIDATE_MARKDOWN: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_TRIVY: false
          FILTER_REGEX_EXCLUDE: (^|/)\.test/nvim/
