---
name: "labeler"

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - name: Apply labels
        uses: actions/labeler@v6
        with:
          configuration-path: .github/labeler.yml
          sync-labels: false
