name: "labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      # checkov:skip=CKV2_GHA_1: required for specific actions
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
