name: PR title

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

concurrency:
  group: pr-title-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pr-title:
    name: pr-title
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Validate the current squash commit title
        uses: ./.github/actions/pr-title
